import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '../public/font/stylesheet.css';
import Header from "./componants/Header";
import Footer from "./componants/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Daniella nicolli",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Header/>
      <main>
        {children}
      </main>
      <Footer/>
         <script src='../public/js/script.js'></script>
      </body>
    </html>
  );
}
